version: "3"
services:
  web:
    container_name: my_web_container
    build: .
    restart: always
    command: /bin/bash -c "alembic upgrade head&& uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
       - "8000:8000"
    volumes:
      - .:/code/
    depends_on:
      - db
    networks:
      - my_network
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: ps_user
      POSTGRES_DB: event_finder_db

    ports:
      - "5433:5432"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
