"""add_models_friendship_uniqdue

Revision ID: 3fee84569a55
Revises: a7090ec585c8
Create Date: 2023-12-23 14:34:30.802244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fee84569a55'
down_revision: Union[str, None] = 'a7090ec585c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
