"""add_balance

Revision ID: 962b9775f09c
Revises: 2412c70f1955
Create Date: 2023-12-19 14:01:09.863430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '962b9775f09c'
down_revision: Union[str, None] = '2412c70f1955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance')
    op.drop_column('events', 'price')
    # ### end Alembic commands ###
