"""modify friends

Revision ID: 2dae7ae429b3
Revises: 7697967cef0a
Create Date: 2025-06-03 15:29:26.636511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dae7ae429b3'
down_revision: Union[str, None] = '7697967cef0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friendships_user_id_fkey', 'friendships', type_='foreignkey')
    op.create_foreign_key(None, 'friendships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.create_foreign_key('friendships_user_id_fkey', 'friendships', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
