"""remove unique even_id in reviews

Revision ID: 05ed04bfcc88
Revises: 2dae7ae429b3
Create Date: 2025-06-09 17:10:16.807923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ed04bfcc88'
down_revision: Union[str, None] = '2dae7ae429b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('review_event_id_key', 'review', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('review_event_id_key', 'review', ['event_id'])
    # ### end Alembic commands ###
