"""add_cascad

Revision ID: 7697967cef0a
Revises: 2dae868db5db
Create Date: 2025-03-13 18:40:34.263989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7697967cef0a'
down_revision: Union[str, None] = '2dae868db5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friendships_friend_id_fkey', 'friendships', type_='foreignkey')
    op.create_foreign_key(None, 'friendships', 'users', ['friend_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.create_foreign_key('friendships_friend_id_fkey', 'friendships', 'users', ['friend_id'], ['id'])
    # ### end Alembic commands ###
